<x-app-layout>
    <x-slot name="header"></x-slot>
    <div class="row">
        <div class="col-lg-12">
            <section class="content">
                <div class="card">
                    <div class="card-body p-0">
                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th>{{__('messages.Reference number')}}</th>
                                    <th>{{__('messages.Payment description')}}</th>
                                    <th>{{__('messages.Payment Status')}}</th>
                                    <th>Date</th>
                                    <th></th>                    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($payment as $pay)
                                <tr>
                                    <td><small>{{$pay->vendor_payment_id}}</small></td>
                                    <td><small>{{$pay->transaction_type}}</small></td>
                                    <td><small>{{$pay->status}}</small></td>
                                    <td><small>{{$pay->created_at}}</small></td>
                                    <td><small>{{$pay->amount}} {{$pay->currency}}</small></td>

                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-lg-8"></div>
                            <div class="col-lg-4 text-center">
                                <!--
                                <small>
                                    {{__('messages.Total generated by the table')}} :  EUR
                                </small>
                                -->
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</x-app-layout>